name: Daily Bias Update
on:
  schedule:
    - cron: '0 9 * * 1-5'   # 4:00 AM New York time, Mon–Fri
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install yfinance pandas requests pytz lxml html5lib
      - run: python daily_bias.py
      - run: |
          git config user.name "Bias Bot"
          git config user.email "bot@github.com"
          git add latest_bias.txt
          git commit -m "Update $(date +'%Y-%m-%d')" || exit 0
          git push